### ISSUE TITLE
How to integrate the CodeMirror XML Lint to CodeMirror 

### ISSUE THREAD

**Issue by Aravinda93** [mikethedj4/html-lint-for-codemirror#1]
I have a `textarea` that has been integrated with the `CodeMirror` using the `Nuxtjs/Vuejs`, I would like to highlight the error and show the `X button` with information next to the line if there are any syntactical errors in XML. I tried many things but nothing seems to work. However, a similar approach works for the `JSON-LINT`.

I came across your response and tried it but nothing is working as I want. Can you please let me know how to create `XML Lint` within CodeMirror to highlight the Syatatical error in XML by showing `X button` with information against the line number?

I have the code sample here in CodeSandbox: https://codesandbox.io/s/great-browser-gfzdf?file=/pages/index.vue

Any help would be really appreciated. Thanks in advance.

**Comment by michaelsboost** [comment]
I suggest referring to the official [Codemirror Repository](https://github.com/codemirror/CodeMirror) by Marijn and asking there.
